server:
  port: 8081
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
      context-path: /music


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/omss?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    # maxActive 连接池的最大值，同一时间可以从池分配的最多连接数量，0时无限制
    maxActive: 20　　
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM user
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面SQL无法统计，‘wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  servlet:
    multipart:
      #单个文件大小
      max-file-size: 100MB
      #总上传的数据大小
      max-request-size: 1000MB
  #    type指定数据源
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  messages:
    basename: i18n.signin

  #禁用缓存
  #controller使用return时，直接写名称，不需要加.html和‘/’
  thymeleaf:
    cache: false
    #在构建URL时预先查看名称的前缀（默认值：classpath:/templates）
    prefix: classpath:/templates/
    #在构建URL时附加查看名称的后缀（默认值：.html)
    suffix: .html
    encoding: UTF-8
    mode: HTML

  jpa:
    #显示SQL
    show-sql: true
    #自动建表方式
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect



##server:
##  port: 8080
##  session-timeout: 30
##  tomcat.max-threads: 0
##  tomcat.uri-encoding: UTF-8
##  servlet:
##    context-path: /music　　#配置访问时的项目名
##spring:
##  devtools:　　　　　　
##  restart:
##    enabled: true　　#这个好像是热加载，每次代码有改动就自动重启，原来的restart ClassLoader 被丢弃，重新创建一个restart ClassLoader，由于需要加载的类相比较少，所以实现了较快的重启时间。
##  datasource:
##    url: jdbc:mysql://localhost:3306/omss?useUnicode=true&characterEncoding=UTF-8&useSSL=true　　#配置数据库的路径
##    username: root　　#数据库登录名
##    password: root   #登陆密码
##    type: com.alibaba.druid.pool.DruidDataSource  #这个可以看一下 https://blog.csdn.net/qq_27191423/article/details/79146855
##    driver-class-name: com.mysql.jdbc.Driver
##    filters: stat
##    maxActive: 20　　#连接池的最大值，同一时间可以从池分配的最多连接数量，0时无限制
##    initialSize: 1　　#连接初始值，连接池启动时创建的连接数量的初始值
##    maxWait: 60000
##    minIdle: 1　　#最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
##    timeBetweenEvictionRunsMillis: 60000
##    minEvictableIdleTimeMillis: 300000
##    validationQuery: select 'x'
##    testWhileIdle: true
##    testOnBorrow: false
##    testOnReturn: false
##    poolPreparedStatements: true 　　#是否对已备语句进行池管理（布尔值），是否对PreparedStatement进行缓存
##    maxOpenPreparedStatements: 20
##
##    jackson:
##      date-format: yyyy-MM-dd HH:mm:ss
##      time-zone: GMT+8
#
##mybatis-plus:
##  mapper-locations: classpath*:mapper/**/*Mapper.xml
##  #实体扫描，多个package用逗号或者分号分隔
##  typeAliasesPackage: com.yudao.platform.entity.*
##  global-config:
##    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
##    id-type: 0
##    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
##    field-strategy: 2
##    #驼峰下划线转换
##    db-column-underline: false
##    #刷新mapper 调试神器
##    refresh-mapper: true
##    #数据库大写下划线转换
##    #capital-mode: true
##    # Sequence序列接口实现类配置
##    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
##    #逻辑删除配置
##    logic-delete-value: 1
##    logic-not-delete-value: 0
##    #自定义填充策略接口实现
##    #meta-object-handler: com.baomidou.springboot.xxx
##    #自定义SQL注入器
##    # sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
##  configuration:
##    map-underscore-to-camel-case: true
##    cache-enabled: false
##    call-setters-on-nulls: true